### ISSUE TITLE
Latest changes are still not available in NPM

### ISSUE THREAD

**Issue by braj1999** [devployment/datajs_vanilla#3]
@devployment Thanks for merging the changes under https://github.com/devployment/datajs_vanilla/pull/2

I did a fresh install today again but seems the changes are still not published. We were not sure if there is anything we can do on this hence requesting you to please have a look whenever you get time.

**Comment by braj1999** [comment]
@devployment Sorry to chase you on this, do let us know when we can expect the changes to be available in NPM

**Comment by devployment** [comment]
Just pushed the latest version to npm. Please check if it's ok now. Had first to find my account again. Did not use this for quite some time. Feel free to re-open again if anything is still wrong.
